### ISSUE TITLE
JOLE no longer uses “URL” label before URL

### ISSUE THREAD

**Issue by rcragun** [tyleransom/jolebib#3]
# Problem

The current `jole.bst` file places the word “URL” before a URL in the references section. 

This is inconsistent with current JOLE guidelines, which give a single example of a reference with a URL:

> Intergovernmental Panel on Climate Change (IPCC). 2011. What is a GCM? http://www.ipcc-data.org/ddc_gcm_guide.html.

Source: https://www.journals.uchicago.edu/journals/jole/instruct-references

# Solution

Two options:

* `\urlprefix` should be removed from the definition of `FUNCTION {format.url}`
* `\urlprefix` should be redefined to be empty

# How I solved this

If I knew how to use Git and GitHub, I would make the change. I fixed this for myself by making the following change to line 1626 of `jole.bst`:

Current version:
```
  "\providecommand{\urlprefix}{URL }"
```

New version:
```
  "\providecommand{\urlprefix}{}"
```

**Comment by tyleransom** [comment]
Thanks for your attention to this detail! I just made the change (editing line 1626 to read "\providecommand{\urlprefix}{}" as you suggested).
